// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzjorefhpnkjsjciyozh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6am9yZWZocG5ranNqY2l5b3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMTE2NjAsImV4cCI6MjA2Njg4NzY2MH0.g3UucvMiCjcV97w-RqtjtkyYg9j2jtoXX0HJHDhs2yY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});